spring.application.name=searchlink

# MongoDB — usa variable de entorno si está presente, localhost en caso contrario
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/searchlink}

# Puerto del servidor
server.port=${PORT:8080}
